[phases.setup]
nixPkgs = ['python312', 'poetry']

[phases.install]
cmds = ['python -m venv --copies /opt/venv', '. /opt/venv/bin/activate', 'pip install poetry==2.1.2', 'poetry install --no-dev --no-interaction --no-ansi']

[phases.build]
cmds = ['poetry run python manage.py collectstatic --noinput']

[start]
cmd = '. /opt/venv/bin/activate && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT'