[phases.setup]
nixPkgs = ['python312', 'poetry']
aptPkgs = ['libpq-dev', 'build-essential', 'libffi-dev'] 

[phases.install]
cmds = [
  'python -m venv --copies /opt/venv',
  '. /opt/venv/bin/activate',
  'pip install poetry==2.1.2',
  'poetry config virtualenvs.create false',
  'poetry install --only main --no-interaction --no-ansi'
]

[phases.build]
cmds = ['poetry run python manage.py collectstatic --noinput']

[start]
cmd = '. /opt/venv/bin/activate && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT'