[phases.setup]
nixPkgs = ['python310', 'poetry']

[phases.install]
cmds = [
    'python -m venv --copies /opt/venv',
    '. /opt/venv/bin/activate',
    'pip install poetry>=1.8.0',
    'poetry config virtualenvs.create false',
    'poetry install --only main --no-interaction --no-ansi'
]

[phases.build]
cmds = ['python manage.py collectstatic --noinput']

[start]
cmd = 'gunicorn config.wsgi:application --workers 4'