swagger: '2.0'
info:
  title: ocelot-cat API
  description: ocelot-cat API
  termsOfService: https://github.com/ocelot-cat/
  contact:
    email: devscarycat@icloud.com
  license:
    name: MIT License
  version: v1
basePath: /api/v1
consumes:
- application/json
produces:
- application/json
securityDefinitions:
  Basic:
    type: basic
security:
- Basic: []
paths:
  /companies/:
    get:
      operationId: companies_list
      description: |-
        기능 : 회사를 만들 수 있습니다.
        허용 : 누구나
      parameters: []
      responses:
        '200':
          description: ''
      tags:
      - companies
    post:
      operationId: companies_create
      description: |-
        기능 : 회사를 만들 수 있습니다.
        허용 : 누구나
      parameters: []
      responses:
        '201':
          description: ''
      tags:
      - companies
    parameters: []
  /companies/departments/{id}/:
    get:
      operationId: companies_departments_read
      description: |-
        기능 : 부서의 상세 정보를 조회/수정/삭제합니다.
        허용 : 회사 오너
      parameters: []
      responses:
        '200':
          description: ''
      tags:
      - companies
    put:
      operationId: companies_departments_update
      description: |-
        기능 : 부서의 상세 정보를 조회/수정/삭제합니다.
        허용 : 회사 오너
      parameters: []
      responses:
        '200':
          description: ''
      tags:
      - companies
    delete:
      operationId: companies_departments_delete
      description: |-
        기능 : 부서의 상세 정보를 조회/수정/삭제합니다.
        허용 : 회사 오너
      parameters: []
      responses:
        '204':
          description: ''
      tags:
      - companies
    parameters:
    - name: id
      in: path
      required: true
      type: string
  /companies/{company_id}/departments/:
    post:
      operationId: companies_departments_create
      description: |-
        기능 : 부서를 만들 수 있습니다.
        허용 : 회사 오너
      parameters: []
      responses:
        '201':
          description: ''
      tags:
      - companies
    parameters:
    - name: company_id
      in: path
      required: true
      type: string
  /companies/{company_id}/invite/:
    post:
      operationId: companies_invite_create
      description: |-
        기능 : 초대 링크를 생성할 수 있습니다.
        허용 : 회사 오너
      parameters: []
      responses:
        '201':
          description: ''
      tags:
      - companies
    parameters:
    - name: company_id
      in: path
      required: true
      type: string
  /companies/{company_id}/members/:
    get:
      operationId: companies_members_list
      description: |-
        기능 : 회사 멤버를 볼 수 있습니다.
        허용 : 관리자와 오너
      parameters: []
      responses:
        '200':
          description: ''
      tags:
      - companies
    parameters:
    - name: company_id
      in: path
      required: true
      type: string
  /companies/{company_id}/members/{user_id}/promote/:
    patch:
      operationId: companies_members_promote_partial_update
      description: |-
        기능 : 회사 멤버를 승격시킬 수 있습니다.
        허용 : 관리자와 오너
      parameters: []
      responses:
        '200':
          description: ''
      tags:
      - companies
    parameters:
    - name: company_id
      in: path
      required: true
      type: string
    - name: user_id
      in: path
      required: true
      type: string
  /companies/{id}/:
    get:
      operationId: companies_read
      description: |-
        기능 : 회사의 상세 정보를 조회/수정/삭제합니다.
        허용 : 회사 오너만
      parameters: []
      responses:
        '200':
          description: ''
      tags:
      - companies
    put:
      operationId: companies_update
      description: |-
        기능 : 회사의 상세 정보를 조회/수정/삭제합니다.
        허용 : 회사 오너만
      parameters: []
      responses:
        '200':
          description: ''
      tags:
      - companies
    delete:
      operationId: companies_delete
      description: |-
        기능 : 회사의 상세 정보를 조회/수정/삭제합니다.
        허용 : 회사 오너만
      parameters: []
      responses:
        '204':
          description: ''
      tags:
      - companies
    parameters:
    - name: id
      in: path
      required: true
      type: string
  /companies/{token}/accept/:
    get:
      operationId: companies_accept_list
      description: |-
        기능 : 초대받은 링크를 수락할 수 있습니다.
        허용 : 누구나
      parameters: []
      responses:
        '200':
          description: ''
      tags:
      - companies
    parameters:
    - name: token
      in: path
      required: true
      type: string
  /notifications/:
    get:
      operationId: notifications_list
      description: ''
      parameters: []
      responses:
        '200':
          description: ''
      tags:
      - notifications
    parameters: []
  /notifications/{notification_id}/mark-read/:
    post:
      operationId: notifications_mark-read_create
      description: ''
      parameters: []
      responses:
        '201':
          description: ''
      tags:
      - notifications
    parameters:
    - name: notification_id
      in: path
      required: true
      type: string
  /products/:
    get:
      operationId: products_list
      description: ''
      parameters: []
      responses:
        '200':
          description: ''
      tags:
      - products
    post:
      operationId: products_create
      description: ''
      parameters: []
      responses:
        '201':
          description: ''
      tags:
      - products
    parameters: []
  /products/{id}/:
    get:
      operationId: products_read
      description: ''
      parameters: []
      responses:
        '200':
          description: ''
      tags:
      - products
    put:
      operationId: products_update
      description: ''
      parameters: []
      responses:
        '200':
          description: ''
      tags:
      - products
    delete:
      operationId: products_delete
      description: ''
      parameters: []
      responses:
        '204':
          description: ''
      tags:
      - products
    parameters:
    - name: id
      in: path
      required: true
      type: string
  /products/{id}/qr/:
    get:
      operationId: products_qr_list
      description: ''
      parameters: []
      responses:
        '200':
          description: ''
      tags:
      - products
    parameters:
    - name: id
      in: path
      required: true
      type: string
  /products/{id}/records/:
    post:
      operationId: products_records_create
      description: ''
      parameters: []
      responses:
        '201':
          description: ''
      tags:
      - products
    parameters:
    - name: id
      in: path
      required: true
      type: string
  /token/:
    post:
      operationId: token_create
      description: |-
        Takes a set of user credentials and returns an access and refresh JSON web
        token pair to prove the authentication of those credentials.
      parameters: []
      responses:
        '201':
          description: ''
      tags:
      - token
    parameters: []
  /users/:
    get:
      operationId: users_list
      description: ''
      parameters: []
      responses:
        '200':
          description: ''
      tags:
      - users
    post:
      operationId: users_create
      description: ''
      parameters: []
      responses:
        '201':
          description: ''
      tags:
      - users
    parameters: []
definitions: {}
