name: Generate API Documentation

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4.0.0 # 정확한 버전 지정

      - name: Set up Python
        uses: actions/setup-python@v4.0.0 # 정확한 버전 지정
        with:
          python-version: "3.13"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.2
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Cache Poetry dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y yamllint dos2unix

      - name: Install Python dependencies
        run: |
          poetry install
          poetry add pyyaml

      - name: Generate API documentation
        env:
          GOOGLE_APPLICATION_CREDENTIALS: google-credentials.json
        run: |
          poetry run python manage.py generate_swagger --format yaml > temp_swagger.yaml
          echo "---" > swagger.yaml
          cat temp_swagger.yaml >> swagger.yaml
          poetry run python manage.py generate_swagger --format json > swagger.json
          dos2unix swagger.yaml
          echo "=== swagger.yaml 내용 ==="
          cat swagger.yaml
          echo "=== swagger.json 내용 ==="
          cat swagger.json

      - name: Fix comma spacing in swagger.yaml
        run: |
          sed -i 's/,/, /g' swagger.yaml

      - name: Format swagger.yaml
        run: |
          poetry run python -c "

      - name: Fix missing colon in swagger.yaml
        run: |
          sed -i 's/^\(\s*\(get\|post\|put\|delete\)\)\s*$/\1:/g' swagger.yaml

      - name: Debug swagger.yaml
        run: |
          head -n 10 swagger.yaml
          echo "Line 2 content:"
          sed -n '2p' swagger.yaml
          echo "Line 3 content:"
          sed -n '3p' swagger.yaml
          echo "Line 4 content:"
          sed -n '4p' swagger.yaml
          echo "Line 5 content:"
          sed -n '5p' swagger.yaml

      - name: Validate YAML
        run: |
          yamllint -c .yamllint.yml swagger.yaml || true  # 임시로 에러 무시

      - name: Validate Swagger YAML
        run: |
          npm install -g swagger-cli
          swagger-cli validate swagger.yaml

      - name: Install redoc-cli
        run: |
          npm install -g redoc-cli

      - name: Convert Swagger to HTML
        run: |
          redoc-cli bundle -o api-docs.html swagger.yaml

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4.0.0
        if: github.ref == 'refs/heads/develop'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
