name: Generate API Documentation

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11" # Django 5.1과 호환되는 버전으로 다운그레이드

      - name: Install system dependencies
        run: sudo apt-get install -y python3-dev

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.5.1
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: |
          poetry install --no-root
          poetry add django-cors-headers

      - name: Create initial migrations
        run: |
          poetry run python manage.py makemigrations users
          poetry run python manage.py makemigrations posts
          poetry run python manage.py makemigrations activities

      - name: Apply migrations
        run: poetry run python manage.py migrate

      - name: Generate API documentation
        run: |
          poetry run python manage.py generate_swagger --format yaml > swagger.yaml
          poetry run python manage.py generate_swagger --format json > swagger.json

      - name: Convert Swagger to HTML
        uses: seeebiii/redoc-cli-github-action@v10
        with:
          args: "bundle -o api-docs.html swagger.yaml"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
