name: Generate API Documentation

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.13"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.5.1
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: |
          poetry install

      - name: Generate API documentation
        run: |
          poetry run python manage.py generate_swagger --format yaml > swagger.yaml
          poetry run python manage.py generate_swagger --format json > swagger.json

      - name: Convert Swagger to HTML
        uses: seeebiii/redoc-cli-github-action@v10
        with:
          args: "bundle -o api-docs.html swagger.yaml"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
