name: Generate API Documentation

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          allow-prereleases: true
          check-latest: true

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3.13-dev

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.2

      - name: Configure Poetry
        run: |
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true
          poetry config experimental.system-git-client true

      - name: Install dependencies
        run: |
          poetry env use python3.13
          poetry install --no-root --sync
